---
output: 
  html_document: 
    toc: true
---



__IMPORTANTE: Para seleccionar proyectos por criterios de Requisitos, Financiamiento y otros, marca y desmarca los filtros (casillas) arriba a la izquierda__ 









### __FONDECYT Regular__

Este concurso financia proyectos de investigación científica o tecnológica 
que conduzcan a nuevos conocimientos o aplicaciones, previstas a través de hipótesis de trabajo. 

Las propuestas deben ser presentadas por investigadores/as de trayectoria demostrada,
sin importar el área o procedencia institucional.

Características:

    - Duración de 2 a 4 años
    - Investigador responsable (IR) con o sin coinvestigadores
    - Evaluación consta de dos etapas: 
      1) evaluación de la productividad del IR, 10 artículos últimos 5 años. 
      Se  debe alcanzar un puntaje sobre el 20% inferior de cada Grupo de Evaluación,  
      para pasar a la siguiente etapa.  
      2) evaluación del proyecto (calidad y viabilidad)
    - Financia: honorarios, tesistas, personal técnico, viajes, gastos de operación,
      bienes de	 capital y colaboración internacional. 
    - Postulación en inglés para algunas áreas (biología-medicina) 
      y a través de plataforma en línea
    - Se requiere patrocinio institucional

#https://anid.cl/proyectos-de-investigacion/fondecyt-regular/

### __FONDECYT Iniciación en Investigación__


Es una iniciativa para formar y fortalecer nuevos científicos. 
Está dirigido específicamente a las nuevas generaciones de profesionales y posgraduados/as.

Características:

    - Duración de 2 a 3 años
    - Postulantes con grado de doctor o especialidad médica de al menos 3 años
    - Se evalúa la trayectoria académica y de investigación, por lo tanto se debe reseñar cómo 
      su capacidad y experiencia académica y de investigación le permitirán desarrollar la 
      investigación propuesta. Se podrán incorporar un máximo de 10 publicaciones de los últimos 5 años
    - La evaluación de los proyectos considera dos etapas. En la primera etapa, la identidad del
      postulante no será de conocimiento de quienes evalúan y considera aspectos de calidad, factibilidad
      y novedad científica o tecnológica de la propuesta. En la segunda etapa se evalúa la trayectoria
      académica y de investigación del/de la postulante 
    - No considera la participación de coinvestigadores/as
    - Financia: honorarios, tesistas, personal técnico, viajes, gastos de operación, bienes de  capital y
      colaboración internacional
    - Postulación en inglés para algunas áreas (biología-medicina) y a través de plataforma en línea
    - Se requiere patrocinio institucional

#https://anid.cl/proyectos-de-investigacion/fondecyt-iniciacion/



### __ANILLOS de Investigación en Ciencia y/o Tecnología y en Ciencias Sociales__

Este concurso busca fomentar el desarrollo científico y/o tecnológico del país, mediante investigación y desarrollo sustentados en un trabajo colaborativo, amplio y multidisciplinario. Promueve la conformación de grupos de investigación científica y/o tecnológica que trabajen bajo el alero de instituciones nacionales de investigación. Se busca fortalecer tanto la generación de conocimiento y el desarrollo de la ciencia y la tecnología, como la formación de capital humano.

Los proyectos tendrán una duración de tres años y las líneas de financiamiento son:

    - Proyecto de Anillo de Investigación en Líneas Temáticas en el área de Ciencias y/o Tecnología. 
    - Financiamiento para tres años de ejecución.
    - Proyecto de Anillo de Investigación en Líneas Temáticas en el área de Ciencias Sociales. 
    
    
Financiamiento para tres años de ejecución.

https://anid.cl/centros-e-investigacion-asociativa/anillos/


### __Fondos Concursables Iniciativa Científica Milenio ICM__

La Iniciativa Milenio es un programa dependiente del Ministerio de Ciencia, Tecnología, Conocimiento e Innovación (MCTCI). Promueve la creación y desarrollo de centros de excelencia (Institutos/Núcleos) para la investigación científica y tecnológica de frontera en el país.

    1. Institutos Científicos Milenio de investigación en Ciencias Naturales y Exactas
      Se trata de grupos de investigadores conformados por:
    - Un(a) director (a) del Centro
    - Director(a) Alterno(a) del Centro Milenio
    - Investigadores(as) Asociados(as)
    - Investigadores(as) Adjuntos(as)
    - Investigadores(as) Jóvenes
    - Investigador(a) Senior
    - Postdoctorados, Estudiantes de Pre y Posgrado, Personal de Gestión Administrativa, Personal Técnico,
      Personal de Comunicaciones.

Plazo de ejecución para Institutos nuevos: 120 meses

    2. Núcleos Milenio en Ciencias Naturales y Exactas  / Núcleos en Ciencias Sociales
       Son grupos conformados por:
    - Un(a) Director (a) del Centro, Investigadores(as) Asociados(as) (mínimo 3, máximo 8)
    - Director(a) Alterno(a) del Centro Milenio
    - Investigador(a) Adjunto(a)
    - Investigador(a) Senior
    - Investigador(a) Joven
    - Posdoctorados, Estudiante de Posgrado, Estudiante Pregrado, Personal de Gestión Administrativa,
      Personal Técnico, Personal de Comunicaciones. 
	
Plazo de ejecución para Núcleos nuevos como renovación: 36 meses

https://www.iniciativamilenio.cl/


### __FONIS Fondo Nacional de Investigación y Desarrollo en Salud__ 

El concurso busca generar y difundir conocimiento a través de proyectos de investigación científica y tecnológica aplicada que contribuyan a la resolución de los problemas prioritarios que se asocian a los objetivos sanitarios vigentes.
Se considera la opción de postular a iniciativas de dos tipos: 

    1. Proyectos de Investigación Nacional y Desarrollo en Salud 
    2. Proyectos Programa Elige Vivir Sano

Características y requerimientos:

    - Duración máxima 24 meses
    - Investigadores/as Principales con patrocinio institucional
    - Instituciones legalmente constituidas: servicios de salud, universidades,
      centros de estudios, municipios, institutos profesionales, institutos de investigación, 
      fundaciones y otras.
    - Financia: honorarios e incentivos de participación, subcontratos, capacitación, equipos, software,
      material fungible, pasajes y viáticos, seminarios, publicaciones, propiedad intelectual y gastos
      generales.
    - Presupuesto ANID corresponde al 90% del monto total. 
    - Postulación en castellano y a través de plataforma en línea.

https://anid.cl/investigacion-aplicada-e-innovacion/investigacion-y-desarrollo-en-salud-fonis/


### __FONDEF: Fondo de Fomento al Desarrollo Científico y Tecnológico__



Concurso IDeA I+D tiene como propósito impulsar el desarrollo de proyectos de investigación e innovación de base científica tecnológica en estrecha colaboración 
con el sector privado, la sociedad civil y el Estado, contribuyendo al aumento de la competitividad, del bienestar y la calidad de vida de la población.

    - Proyectos de I+D precompetitivos: se orientan al desarrollo de tecnologías, conocimiento e
      innovación en la forma de productos, servicios y/o procesos que puedan ser transferidos y,
      posteriormente, comercializados en mercados de tecnologías, servicios o de bienes de inversión,
      intermedios o finales.
    - Proyectos de I+D de interés público: se orientan al desarrollo de tecnologías, conocimiento e
      innovación para resolver problemas propuestos por entidades públicas o de la sociedad civil. Los
      resultados de los proyectos serán de dominio y uso público en Chile.

Nivel de madurez tecnológica: TRL 2 como mínimo

Líneas de financiamiento: proyectos genéricos y proyectos temáticos.

Se entiende por proyectos genéricos a aquellos que abordan problemas, oportunidades o desafíos de todos los sectores del quehacer nacional. La aproximación puede ser en un sector específico o multisectorial. Entre los sectores de mayor relevancia figuran: Alimentos; Agropecuario; Forestal; Manufactura; Construcción e Infraestructura; Minería; Energía; Agua y Sector Sanitario; Pesca y Acuicultura; TIC; Educación; Salud; Turismo; Logística y Transporte; Comercio; Servicios Financieros; e Industria Creativa.

Los proyectos temáticos comprenden aquellos orientados a resolver desafíos nacionales en un sector o temas definidos por el Ministerio de Ciencia, Tecnología, Conocimiento e Innovación. 
Las temáticas para el concurso han sido las siguientes:

    - Resiliencia a la crisis climática, ambiental e hídrica y seguridad alimentaria.
    - Descarbonización justa: tecnologías de hidrógeno verde, litio y electromovilidad.
    - Transformación digital: inteligencia artificial, tecnologías aeroespaciales, análisis y uso de datos
      satelitales y astroingeniería.
    - Convivencia, cohesión social y seguridad ciudadana.

Plazo de ejecución de hasta  24 meses

Aporte de institución Beneficiaria: al menos 30% del monto solicitado a FONDEF (incremental y/o no incremental)

Aporte de Asociadas: al menos un 15% del monto solicitado a FONDEF (incremental y/o no incremental)

https://anid.cl/concursos/concurso-idea-id-2025/

ANID: https://www.anid.cl/


### __Start Up Ciencia - Investigación Aplicada__


Promover el crecimiento y el fortalecimiento en etapa temprana de las empresas de base científico-tecnológica (EBCT) en Chile, a través del cofinanciamiento y el apoyo técnico en el proceso de desarrollo tecnológico, innovación, validación técnica y de negocios de los nuevos productos y/o servicios, facilitando su entrada a los mercados nacionales y/o internacionales.

Plazo de ejecución de hasta 12 meses. 

El aporte pecuniario corresponde, al menos, al 15% del costo total del proyecto.

Bonificación: empresas lideradas por mujeres y empresas pertenecientes a regiones distintas a la Metropolitana

https://anid.cl/investigacion-aplicada-e-innovacion/startup-ciencia/


### __CORFO, Corporación de Fomento de la Producción__ 

es un servicio público descentralizado, con patrimonio propio y personalidad jurídica.

La misión de CORFO es fomentar la inversión, la innovación y el emprendimiento, fortaleciendo, además, el capital humano y el desarrollo tecnológico para mejorar la productividad del país y alcanzar posiciones de liderazgo mundial en materia de competitividad.
https://corfo.cl/sites/cpp/programasyconvocatorias


### __CORFO - Programa Start-Up Chile Líneas 1, 2 y 3__:

Línea 1: “Build”: atraer, potenciar y crear nuevos emprendimientos tecnológicos de alto impacto con visión global. 
Para aquellos proyectos con un desarrollo comercial de hasta 12 meses y que se encuentran en etapa de idea, concepto o de prototipado.

    - Plazo: La ejecución de los proyectos deberá ser de 4 meses.
    - Subsidio Corfo: para el/la beneficiario/a. Corfo cofinanciará hasta el 90% del costo total del
      proyecto.
    - Pago de Overhead a la Entidad Patrocinadora para Start-Up Chile.
      

Línea 2: “Ignite”: generar un impacto socioeconómico en Chile, a través del apoyo a emprendimientos tecnológicos innovadores que permitan sofisticar y/o diversificar la matriz económica del país.
Para aquellos proyectos con desarrollo comercial de hasta 36 meses, que utilicen a Chile como plataforma, y que cuenten, al menos, con un producto mínimo viable (MVP) o prototipo funcional de la solución.

    - Plazo: La ejecución de los proyectos de hasta 6 meses.
    - Subsidio Corfo para el/la beneficiario/a. Corfo cofinanciará hasta el 80% del costo total del
      proyecto. Respecto de la líder del proyecto cuyo sexo registral sea femenino, Corfo cofinanciará
      hasta el 90% del costo total del proyecto.
    - Pago de Overhead a la Entidad Patrocinadora para Start-Up Chile.

Línea 3: “Growth”: Generar un impacto socioeconómico en Chile, a través del apoyo a emprendimientos tecnológicos innovadores que permitan sofisticar y/o diversificar la matriz económica del país.
Se deberá demostrar que el proyecto global (tanto en Chile como en el extranjero) ha tenido ingresos por ventas, en los 12 meses anteriores al mes de apertura del concurso.

    - Plazo de ejecución de los proyectos de hasta 12 meses.
    - Subsidio Corfo: cofinanciará hasta el 50 % del costo total del proyecto. Respecto de la líder del
      proyecto cuyo sexo registral sea femenino, Corfo cofinanciará hasta el 60% del costo total del
      proyecto.
    - Pago de Overhead a la Entidad Patrocinadora para Start-Up Chile. 

https://startupchile.org/

### __Fundación para la Innovación Agraria FIA__

La Fundación para la Innovación Agraria (FIA) es la agencia de innovación del Ministerio de Agricultura. Su misión es contribuir a la solución eficiente de desafíos estratégicos del sector silvoagropecuario nacional y/o de la cadena agroalimentaria asociada, por medio del fomento, articulación y difusión tecnológica de procesos de innovación orientados al desarrollo sustentable.

 http://www.fia.cl/convocatorias/


### __Superintendencia de Seguridad Social (SUSESO)__


Concurso destinado para el desarrollo de proyectos de investigación e innovación, relacionadas con la prevención de los riesgos de accidentes del trabajo y de enfermedades profesionales así como también con la atención de salud, rehabilitación y reinserción laboral derivadas de la Ley N°16.744, que constituyan un aporte efectivo y generen conocimientos en materias de seguridad y salud en el trabajo.
    
    - Se financian honorarios y remuneraciones, equipos, softwares, materiales, realización de exámenes o
      servicios de terceros, gastos en locomoción, pasajes y viáticos para el desarrollo del proyecto
    - Gastos de administración
    - Se financiarán las etapas de ejecución, seguimiento, control, publicación y difusión de resultados

Proyectos de investigación:

Subsidio total 24 meses 

Plazo de 12 meses para revisiones panorámicas o revisiones sistemáticas o de análisis documental, métodos de estudio que no requieren trabajo en terreno. 

### __Proyectos de iniciación en innovación:__

Subsidio total 12 meses

### __Proyectos de continuidad en innovación:__

Son proyectos que han superado las primeras etapas de innovación y tiene por objetivo el apoyo al diseño e implementación de un prototipo o piloto de innovación. Subsidio total 12 meses.

Proyectos de implementación en innovación
Son proyectos avanzados que están en etapa de implementación de la innovación en el sector privado o público y que podrán estar destinados a la marcha blanca y evaluación de la innovación. Subsidio 24 meses.

Los proyectos de continuidad y de implementación en innovación deberán contar con la participación de una organización o entidad en donde se implementará la innovación

https://www.suseso.cl/605/w3-article-734803.html


###__FONDOS CONCURSABLES VICERRECTORÍA DE INVESTIGACIÓN Y DESARROLLO (VID)__

La Vicerrectoría de Investigación y Desarrollo (VID) de la Universidad de Chile, tiene la misión de articular la investigación, innovación y creación artística que se realiza en las unidades académicas de la Universidad para contribuir al desarrollo del país y su inserción global.

El objetivo de esta Vicerrectoría se logra de la siguiente manera:

    - Construyendo redes de investigación transdisciplinarias.
    - Realizando actividades de extensión con escuelas y municipalidades.
    - Estableciendo acuerdos y convenios con instituciones del Estado.
    - Firmando contratos de licencias con empresas. Generando normativas y reglamentos académicos.
    - Generando distintas plataformas de difusión social.
    - Consolidando un cambio cultural en innovación y creación artística.
    - Instalando a la internacionalización como un valor transversal en el quehacer universitario.

La Vicerrectoría cuenta con concursos internos a los cuales pueden postular los/las académicos/as de la Universidad de Chile. Dentro de ellos podemos señalar aquellos que tienen actualmente convocatorias anuales:

### __U-Inicia. Inserción de nuevos académicos__

    - Su objetivo es facilitar la inserción productiva y sustentable de académicos de excelencia, de
      contratación reciente (últimos 24 meses)
    - Dirigido a académicos/as jóvenes que posean contrato académico de al menos 22 horas
    - Grado académico de Doctor o Especialidad Médica, obtenido en los últimos 5 años
    - Los interesados deben alcanzar una productividad científica relevante y desarrollar una línea de
      investigación independiente.
    - El postulante no debe haberse adjudicado ningún financiamiento previo (VID, CONICYT)
    - Periodo máximo de ejecución: 24 meses.
    - Financia: material fungible, equipos, bibliografía, publicaciones, viajes y viáticos nacionales,
      insumos laboratorio,tesistas, personal técnico y/o de apoyo, contratación de estudios de campo,
      entre otros.
    - Se deberá postular a concursos FONDECYT Regular, Iniciación u otro equivalente.

### __U-Apoya, Ayuda de Viaje para Potenciar Productividad Académica__

    - Destinado a académicos con postgrado (Mg, PhD, o Especialidad) y contrato de al menos 22 horas. 
    - Financia como máximo dos Ayudas de Viaje por académico/a en un período de 5 años.
    - Viajes para presentaciones orales como conferencistas en congresos nacionales o internacionales y
      estadías de investigación en el extranjero por un máximo 3 meses 

### __Proyecto de Enlace. Programa de Apoyo a Proyectos de Enlace con Concurso Fondecyt Regular__

    - Su objetivo es mantener activas líneas de investigación de académicos que no renovaron su proyecto
      FONDECYT en el Concurso Regular anterior, habiendo sido investigador activo en este concurso en los
      últimos años. 
    - Podrán    participar   en   este   concurso  los/las investigadores/as   responsables  (IR)
      de proyectos no seleccionados en el último Concurso FONDECYT  Regular habiendo finalizado  un
      Proyecto FONDECYT Regular  a partir  de marzo  del año anterior  y que presenten un  nuevo proyecto
      al concurso FONDECYT Regular siguiente.
    - Con el propósito de lograr la transición entre el concurso FONDECYT de Iniciación y el Regular,
      pueden postular investigadores/as que finalizaron un proyecto de Iniciación FONDECYT y que no
      lograron adjudicarse un proyecto FONDECYT en el Concurso Regular reciente.
    - Duración: 12 meses 

